In [1]:
import pandas as pd
import re

In [10]:
# all_sheets = pd.read_excel("../app/data/galectins_id_cleaned.xlsx", sheet_name=None)
all_sheets = pd.read_excel("../app/data/Galectins_GlyTouCanID_Updated.xlsx", sheet_name=None)
data = {}
for glectin in all_sheets:
  temp = all_sheets[glectin]
  # print(temp.columns[2].split(',')[1].strip())
  # data[glectin]
  temp['test'] = 3
  temp = temp.rename(columns={'test':"ff"})
  display(temp.head())

#   data[glectin] = temp[temp["Glycan"].notna()].reset_index(drop=True)
#   data[glectin] = data[glectin].drop(columns=['Symbol'])

,ID,Glycan,"Kd, mM",stdev_Kd,"Kd, mM.1",1/Kd,SD,GlyTouCan ID,ff
0,L1,β-D-Gal-(1→4)-β-D-GlcNAc(1→3)-β-D-Gal(1→4)-β-D...,0.045455,0.008264,0.05 ± 0.01,2.2,0.4,G70000DB,3
1,L2,α-D-Neu5Ac(2→3)-β-D-Gal(1→3)-[α-L-Fuc(1→4)]-β-...,0.333333,0.111111,0.33 ± 0.11,0.3,0.1,G40184OL,3
2,L3,α-L-Fuc(1→2)-β-D-Gal(1→3)-β-D-GlcNAc(1→3)-β-D-...,0.142857,0.020408,0.14 ± 0.02,0.7,0.1,G19490AF,3
3,L4,β-D-Gal(1→3)-[α-L-Fuc(1→4)]-β-D-GlcNAc(1→3)-β-...,0.250000,0.062500,0.25 ± 0.06,0.4,0.1,G21067JW,3
4,L5,β-D-Gal-(1→4)-β-D-GlcNAc-(1→3)-β-D-Gal-(1→4)-β...,0.076923,0.005917,0.08 ± 0.01,1.3,0.1,G97732OH,3

,ID,Glycan,"Kd, uM",stdev_Kd,"Kd, uM.1",1/Kd,SD,GlyTouCan ID,ff
0,L1,β-D-Gal-(1→4)-β-D-GlcNAc(1→3)-β-D-Gal(1→4)-β-D...,10.752688,0.231241,11 ± 0.2,9.3,0.2,G70000DB,3
1,L2,α-D-Neu5Ac(2→3)-β-D-Gal(1→3)-[α-L-Fuc(1→4)]-β-...,15.151515,0.459137,15 ± 0.5,6.6,0.2,G40184OL,3
2,L3,α-L-Fuc(1→2)-β-D-Gal(1→3)-β-D-GlcNAc(1→3)-β-D-...,11.627907,0.135208,12 ± 0.1,8.6,0.1,G19490AF,3
3,L4,β-D-Gal(1→3)-[α-L-Fuc(1→4)]-β-D-GlcNAc(1→3)-β-...,8.333333,0.416667,8 ± 0.4,12,0.6,G21067JW,3
4,L5,β-D-Gal-(1→4)-β-D-GlcNAc-(1→3)-β-D-Gal-(1→4)-β...,7.692308,0.591716,8 ± 0.6,13,1.0,G97732OH,3

,ID,Glycan,"Kd, mM",stdev_Kd,"Kd, mM.1",1/Kd,SD,GlyTouCan ID,ff
0,L1,β-D-Gal-(1→4)-β-D-GlcNAc(1→3)-β-D-Gal(1→4)-β-D...,0.111111,0.012346,0.11 ± 0.01,0.9,0.1,G70000DB,3
1,L2,α-D-Neu5Ac(2→3)-β-D-Gal(1→3)-[α-L-Fuc(1→4)]-β-...,0.25,0.0625,0.25 ± 0.06,0.4,0.1,G40184OL,3
2,L3,α-L-Fuc(1→2)-β-D-Gal(1→3)-β-D-GlcNAc(1→3)-β-D-...,0.125,0.03125,0.13 ± 0.03,0.8,0.2,G19490AF,3
3,L4,β-D-Gal(1→3)-[α-L-Fuc(1→4)]-β-D-GlcNAc(1→3)-β-...,0.1,0.01,0.10 ± 0.01,1,0.1,G21067JW,3
4,L5,β-D-Gal-(1→4)-β-D-GlcNAc-(1→3)-β-D-Gal-(1→4)-β...,0.142857,0.020408,0.14 ± 0.02,0.7,0.1,G97732OH,3

,ID,Glycan,"Kd, uM",stdev_Kd,"Kd, uM.1",1/Kd,SD,GlyTouCan ID,ff
0,L1,β-D-Gal-(1→4)-β-D-GlcNAc(1→3)-β-D-Gal(1→4)-β-D...,14.285714,1.632653,14.3 ± 1.6,7,0.8,G70000DB,3
1,L2,α-D-Neu5Ac(2→3)-β-D-Gal(1→3)-[α-L-Fuc(1→4)]-β-...,2.808989,0.015781,2.8 ± 0.0,35.6,0.2,G40184OL,3
2,L3,α-L-Fuc(1→2)-β-D-Gal(1→3)-β-D-GlcNAc(1→3)-β-D-...,4.048583,0.32782,4.0 ± 0.3,24.7,2.0,G19490AF,3
3,L4,β-D-Gal(1→3)-[α-L-Fuc(1→4)]-β-D-GlcNAc(1→3)-β-...,2.409639,0.116127,2.4 ± 0.1,41.5,2.0,G21067JW,3
4,L5,β-D-Gal-(1→4)-β-D-GlcNAc-(1→3)-β-D-Gal-(1→4)-β...,28.571429,0.816327,28.6 ± 0.8,3.5,0.1,G97732OH,3

In [ ]:
# with pd.ExcelWriter("galectins_id_cleaned.xlsx") as writer:
#   for glectin, df in data.items():
#     df.to_excel(writer, sheet_name=glectin, index=False)

In [ ]:
# with pd.ExcelWriter("output.xlsx") as writer:
#   for glectin in data:
#     df = data[glectin]
#     df.to_excel(writer, sheet_name=re.sub(r'[\\/*?:[\]]', '_', glectin), index=False)

dict

In [6]:
test = all_sheets['hGal-9N']
test[(test["GlyTouCan ID"] == "G94468TS")]

     ID                               Glycan  Kd 1/Kd   SD GlyTouCan ID
23  L24  β-D-Gal(1→4)-[α-L-Fuc(1→3)]-β-D-Glc  NB   NB  0.0     G94468TS

In [ ]:
# temp = data['hGal-1']

In [8]:
import requests
from bs4 import BeautifulSoup

url = "https://image.glycosmos.org/snfg/png/G70000DB"
response = requests.get(url)

In [ ]:
byte_str = response.contents

In [15]:
import io
from PIL import Image

In [16]:
img = Image.open(io.BytesIO(byte_str))

img.show()